GET http://localhost:3000/products


### GET BY ID
GET http://localhost:3000/products/22

###POST
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Keyboard",
  "price": 49.99,
  "quantity": 1
}

###PUT
PUT  http://localhost:3000/products/6a15317b86da68c3d4f2dce2
Content-Type: application/json

{
    "name": "test",
    "price": 1000,
    "quantity": 1

}

###Del
DELETE   http://localhost:3000/products/6a153c6023d16c538ea02ec7
